### ISSUE TITLE
LMMS translated futur website

### ISSUE THREAD

**Issue by trebmuh** [liushuyu/lmms-translations#12]
Hi @liushuyu : could I suggest the LMMS software picture:
![capture du 2017-10-20 23-22-28](https://user-images.githubusercontent.com/8705846/31842276-aa52ddf2-b5ed-11e7-8d3e-d38a397a2cf6.png)
to be translated into French for someone browsing the website in French (and for other language where the software is translated as well)? This way, it would show people that the software is talking in their languages, no need to talk English to be able to use it. For a non-English speaker, it would be **really** appealing.

**Comment by liushuyu** [comment]
Yes, but I am thinking of ways to do it. If it were a SVG format image, that would be easy, just replace the text and it would be ready to go.

For now, to accomplish the same goal,  we need to have multiple pictures available and specify the URL to the picture of each language.

**Comment by trebmuh** [comment]
OK, I'm happy you're on the wave. Unfortunately, I can't be of any help here, unless you ask me to provide a French localized capture. In such a case, please let me know.

**Comment by liushuyu** [comment]
Unfortunately they have totally refused this proposal.

**Comment by trebmuh** [comment]
Sad. Curiosity: who are "they"?

**Comment by liushuyu** [comment]
> Curiosity: who are "they"?

The website is not being solely developed by me, by saying "they" I meant other website developers and designers.

**Comment by trebmuh** [comment]
OK, thanks for the explanation. Sorry to hear that since I think it could really make a difference for the non-english speaker but anyway, maybe there is a lot of work involved with doing that and the devs have other priorities.
I'm closing it now.
Is there a better for general discussion around the website? Maybe here: https://github.com/lmms/lmms.io/ ?

**Comment by trebmuh** [comment]
OK, thanks for the explanation. Sorry to hear that since I think it could really make a difference for the non-english speaker but anyway, maybe there is a lot of work involved with doing that and the devs have other priorities.
I'm closing it now.
@liushuyu : is there a better for general discussion around the website for the next time? Maybe here: https://github.com/lmms/lmms.io/ ?
