### ISSUE TITLE
Update of the current lmms.io file

### ISSUE THREAD

**Issue by trebmuh** [liushuyu/lmms-translations#14]
Hi @liushuyu ,
now that https://github.com/LMMS/lmms.io/pull/248 as been merged, would you like me to move forward? Do I need to wait for the file here to be updated? Or can I just make a patch against the current FR translation here and that'd be good for you?
Please, let me know.

**Comment by liushuyu** [comment]
Updated in f640748a6f37af4036d18d69c3d8a18f1b41caff
