### ISSUE TITLE
Futur website: missing a few FR translations

### ISSUE THREAD

**Issue by trebmuh** [liushuyu/lmms-translations#17]
Hi @liushuyu ,
Some of the FR translations for the futur website are not done and keep displaying the English strings (such as "Take a peek." or "Featuring:" for examples). 
Can you please sync the files here then I can investigate what's wrong?
Thanks.

**Comment by liushuyu** [comment]
Hi @trebmuh ,

The problem is that we currently rely on manual update the translations from here to the server. So the translations are not immediately sync'ed to the server when it's merged here (or when I received patches from emails or completed on translation platforms).

I'll do a sync shortly after that, sorry for the inconvenience.

Thanks

**Comment by trebmuh** [comment]
Thanks for the explanation @liushuyu . Don't rush to update the website just for me, just ping me later when it's done.

**Comment by liushuyu** [comment]
Hi,

We are happy to announce that our new website will replace our old one in 24 hours. 
There are still untranslated strings (newly added) however, but not very much.

**Comment by trebmuh** [comment]
@liushuyu : French translation updated to 100% https://github.com/liushuyu/lmms-translations/pull/19

**Comment by liushuyu** [comment]
Hi,

Are you also interested in translating subtitles for the promotional video(s)? I'll update that as soon as they are available.

**Comment by trebmuh** [comment]
@liushuyu : could be (depending the workload needed and the free time I've got). Let me know when they're available.

**Comment by trebmuh** [comment]
@liushuyu : I can see that the new website is online, congraz !

Those last translations (from https://github.com/liushuyu/lmms-translations/pull/19 ) doesn't seem to have reached the website yet. Is there any estimated time for this to happen?

**Comment by liushuyu** [comment]
>Those last translations (from #19 ) doesn't seem to have reached the website yet. Is there any estimated time for this to happen?

This takes time and new strings are introduced in the first day of the deployment, if you can finish the translation (yet again) it will of course makes its way to the website since the website now should be finalized.

**Comment by trebmuh** [comment]
@liushuyu : done in https://github.com/liushuyu/lmms-translations/pull/20

**Comment by trebmuh** [comment]
It looks to be good here.
I'm closing then.

**Comment by liushuyu** [comment]
So The Best of LMMS V has announced, which brought new strings. Do you still have time to work on it?

**Comment by trebmuh** [comment]
@liushuyu : done!

By the way, it looks like the headers are reinitialised when you update the *.po files which unfortunately doesn't keep the copyright for the previous translators. I manually re-added 2 of the previous translators that I'm aware of by looking at the previous PR I submitted here. If you would find a way to ensure that the headers are kept from one update to the next one, it'd be better/easier/safier.

Cheers.

**Comment by liushuyu** [comment]
>By the way, it looks like the headers are reinitialised when you update the *.po files which unfortunately doesn't keep the copyright for the previous translators. I manually re-added 2 of the previous translators that I'm aware of by looking at the previous PR I submitted here. If you would find a way to ensure that the headers are kept from one update to the next one, it'd be better/easier/safier.

I am aware of this, since we are using a translation management platform to store the translations, and your profile does not exist in their system so each time I update the files the headers are reinitialized.
I can manually restore them each time doing the synchronize if you want to.

For the credits problem, I'll create a `CONTRIBUTOR` file for our brilliant translators so that you guys will be properly credited.

**Comment by trebmuh** [comment]
OK. Thanks for your quick answer @liushuyu .

**Comment by trebmuh** [comment]
@liushuyu : the [The Best of LMMS Vol. 5](https://lmms.io/competitions/) paragraph is still in English here. Can I ask you an ETA for the site to be refreshed?

**Comment by liushuyu** [comment]
>@liushuyu : the The Best of LMMS Vol. 5 paragraph is still in English here. Can I ask you an ETA for the site to be refreshed?

Currently I am testing a translation synchronization bot, but it was not very stable at the moment, I have manually updated the website, it should be refreshed now

**Comment by trebmuh** [comment]
[It is](https://lmms.io/competitions/?lang=fr_FR). Thanks @liushuyu !
I've made a new PR to improve the translation. Please, see here : https://github.com/liushuyu/lmms-translations/pull/22

**Comment by trebmuh** [comment]
@liushuyu I can see that the Competition n°5 went into the "past competitions" and the text displayed is now back to English.

Is there anything that need to be translated to have it back to French?

**Comment by liushuyu** [comment]
>Is there anything that need to be translated to have it back to French?

Yes, I haven't synchronized the translations, it will take some time though.

**Comment by trebmuh** [comment]
@liushuyu : thanks for the answer. Let me know when I can help.

**Comment by trebmuh** [comment]
@liushuyu it looks like the Competition V paragraph isn't translated in French while I thought I had it done. Can you please update me about that please?

**Comment by liushuyu** [comment]
>@liushuyu it looks like the Competition V paragraph isn't translated in French while I thought I had it done. Can you please update me about that please?

I am not aware of that until you reminded me today. I will try to investigate the issue.

**Comment by trebmuh** [comment]
@liushuyu after a second thought, it could well be because I translated it when the competition was announced/going but now, it went to "past competition".

**Comment by trebmuh** [comment]
@liushuyu ping

**Comment by trebmuh** [comment]
Done [here](https://github.com/liushuyu/lmms-translations/commit/86ab15d33ddb32a5e29af8e0fa866b38feb0cb2d).

_Closing this thread which is starting to be toooooo long._
