### ISSUE TITLE
update

### ISSUE THREAD

**Issue by trebmuh** [liushuyu/lmms-translations#27]
@liushuyu can you please update the French translation files for the software? Someone found a typo (LDASPA instead of LADSPA) and told me about it. I'd like to fix it.
Thanks.

**Comment by liushuyu** [comment]
The translations have been updated. Thanks for your continued support!

**Comment by trebmuh** [comment]
Thanks @liushuyu . Done in #28 . Can you please merge this one? Thanks.

**Comment by trebmuh** [comment]
:+1:
