### ISSUE TITLE
one missing translation string

### ISSUE THREAD

**Issue by trebmuh** [liushuyu/lmms-translations#6]
Hi @liushuyu : I found one missing translation "LADSPA Plugin Browser"
https://github.com/LMMS/lmms/blob/master/plugins/ladspa_browser/ladspa_browser.cpp#L51
I mean, it's not translatable in the ts files.
Can you do something about it?

**Comment by liushuyu** [comment]
Hi @trebmuh : 

I remembered I talked to other developers about this long before, their opinion was to keep it as-is, and I found after translating it, sometimes LMMS will misbehave when you open LADSPA plugin browser. I am a little busy with my study now, but will try to figure out a solution ASAP.

Thanks for your kind reminder.

**Comment by trebmuh** [comment]
No worries. I'm hard-patching it (with a quilt patch before build time) when building it for my distribution, so it's not a big deal. That said, it would be neat to allow its translation for the world outside my distro.

**Comment by trebmuh** [comment]
Closing here since I [mentioned it here](https://github.com/LMMS/lmms/pull/4019).
